### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by imhta**

### CODE REVIEW

**Comment by JamesOkunlade** [comment]
Under Review By James Okunlade

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
### Hello devs!!

You seem to have written cool and proper tests but sadly I couldn't run `RSpec` on it successfully. 

I keep getting colorize errors. I shouldn't need to run more than `RSpec` to run your test. Please update your `README.md` file to contain the details on how to run your tests if it ran on your computer.

Request for another review when you're done.

Happy coding!

**Comment by JamesOkunlade** [comment]
### Under review by James

**Review by JamesOkunlade — APPROVED** [review]
This is fine. :+1::+1: I had to uncomment you're `require colorize` line though. Ensure to do same before merging.

Moving on, you should not work on the develop branch directly but instead a feature branch then make a pull request to merge `feature-branch` to `development`.

Good luck with your future projects.

**Comment by imhta** [comment]
We used to work on local feature branch. And even we are following git flow.

**Pull request merged**
